/**
 * ============================================================================
 * AUTH SERVICE — Frontend Service Layer for Authentication
 * ============================================================================
 *
 * This service handles all authentication-related API calls.
 * It provides both a REAL implementation (using fetch) and a MOCK implementation
 * (using setTimeout) for development without a running backend.
 *
 * ─── DATABASE ALIGNMENT ───
 * PostgreSQL Table: `users`
 *   - id:            UUID (Primary Key, generated by DB)
 *   - email:         VARCHAR(255) (Unique — used as "Username" on the form)
 *   - password_hash: TEXT (Hashed on backend, NEVER sent from frontend)
 *   - role:          ENUM ('member', 'admin')
 *
 * ─── API ENDPOINT ───
 * POST /api/auth/login
 *   Request:  { "username": "...", "password": "..." }
 *   Success:  { "success": true, "token": "jwt...", "user_id": "uuid...", "role": "member"|"admin" }
 *   Error:    { "success": false, "message": "Invalid credentials." }
 *
 * ─── ROLE DETECTION ───
 *   No `role_request` field is sent from the frontend.
 *   The backend looks up the user by email, verifies the password,
 *   and returns the role directly from the `users.role` column.
 *   Admin users simply have role='admin' in the database.
 *
 * ─── TEST ACCOUNTS (for mock) ───
 *   Admin:  admin_test@smartgym.com  / admin123
 *   Member: user_test@smartgym.com   / user123
 *
 * ============================================================================
 */

// Toggle this to switch between mock and real API calls.
// Set to `false` when the backend is running.
const USE_MOCK = true;

// Base URL for the real API (matches the Express.js backend)
const API_BASE_URL = "http://localhost:8000/api";

/**
 * ─── MOCK LOGIN ───
 * Simulates the backend POST /api/auth/login endpoint.
 * Uses setTimeout with 1.5s latency to mimic network delay.
 *
 * The backend determines the user's role automatically from the database.
 * No role_request is needed — just match email + password.
 *
 * @param {string} username  - The user's email (maps to `users.email` in DB)
 * @param {string} password  - The user's plain password (backend would hash-compare)
 * @returns {Promise<object>} - Resolves with success payload, rejects with error payload
 */
function apiMockLogin(username, password) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // ── Mock user database ──
      // These entries simulate rows in the PostgreSQL `users` table.
      // `password_hash` would be bcrypt-hashed on the real backend.
      const mockUsers = [
        {
          id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",    // users.id (UUID)
          email: "admin_test@smartgym.com",                // users.email
          password: "admin123",                            // Plain — backend compares hash
          role: "admin",                                   // users.role ENUM
        },
        {
          id: "f9e8d7c6-b5a4-3210-fedc-ba0987654321",    // users.id (UUID)
          email: "user_test@smartgym.com",                 // users.email
          password: "user123",                             // Plain — backend compares hash
          role: "member",                                  // users.role ENUM
        },
      ];

      // ── Find user by email and password ──
      // The backend would: SELECT * FROM users WHERE email = $1
      // then: bcrypt.compare(password, user.password_hash)
      const user = mockUsers.find(
        (u) => u.email === username && u.password === password
      );

      if (!user) {
        // ── Error Response (matches backend JSON structure) ──
        reject({
          success: false,
          message: "Invalid credentials. Please check your email and password.",
        });
        return;
      }

      // ── Success Response (matches backend JSON structure) ──
      // The role is returned directly from the user's DB record.
      // No role_request needed — admin accounts return "admin", members return "member".
      resolve({
        success: true,
        token: `mock_jwt_token_${user.role}_${Date.now()}`,  // Simulated JWT
        user_id: user.id,                                     // Maps to users.id
        role: user.role,                                      // Maps to users.role (auto-detected)
      });
    }, 1500); // 1.5 second simulated network latency
  });
}

/**
 * ─── REAL LOGIN ───
 * Sends a POST request to the actual Express.js backend.
 * Payload structure: { username, password }
 *
 * The `username` field on the frontend maps to the `email` column
 * in the PostgreSQL `users` table. The backend handles this mapping
 * and returns the user's role automatically.
 *
 * @param {string} username    - User's email address
 * @param {string} password    - User's plain password
 * @returns {Promise<object>}  - The parsed JSON response from the backend
 */
async function apiRealLogin(username, password) {
  const response = await fetch(`${API_BASE_URL}/auth/login`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    // ── Request Payload ──
    // Only username (email) and password are sent.
    // The backend determines the role from the `users.role` DB column.
    body: JSON.stringify({
      username,       // Maps to users.email in the database
      password,       // Backend will bcrypt.compare against users.password_hash
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw data; // Throw the error object so the component can catch it
  }

  return data;
}

/**
 * ─── PUBLIC API ───
 * Main login function used by components. Automatically routes
 * to either the mock or real implementation based on USE_MOCK flag.
 *
 * @param {string} username    - Email address used as login identifier
 * @param {string} password    - User's password
 * @returns {Promise<object>}
 */
export async function loginUser(username, password) {
  if (USE_MOCK) {
    return apiMockLogin(username, password);
  }
  return apiRealLogin(username, password);
}

/**
 * ─── MOCK REGISTER ───
 * Simulates the backend POST /api/v1/users/ endpoint.
 * Uses setTimeout with 1.5s latency to mimic network delay.
 *
 * Checks for duplicate emails against the mock user list.
 * On success, returns a user object matching the backend response.
 *
 * @param {string} fullName  - Maps to users.full_name
 * @param {string} email     - Maps to users.email (UNIQUE)
 * @param {string} password  - Backend would hash this before storing
 * @returns {Promise<object>}
 */
function apiMockRegister(fullName, email, password) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // ── Check for duplicate emails ──
      const existingEmails = [
        "admin_test@smartgym.com",
        "user_test@smartgym.com",
        "test2@example.com",
        "nguyenvanb@example.com",
      ];

      if (existingEmails.includes(email.toLowerCase())) {
        reject({
          success: false,
          message: "An account with this email already exists.",
        });
        return;
      }

      // ── Success Response (matches backend POST /api/v1/users/ response) ──
      resolve({
        success: true,
        user_id: Math.floor(Math.random() * 1000) + 10,
        full_name: fullName,
        email: email,
        role: "member",
      });
    }, 1500);
  });
}

/**
 * ─── REAL REGISTER ───
 * Sends a POST request to POST /api/v1/users/
 * Payload: { full_name, email, password }
 *
 * @param {string} fullName  - User's full name
 * @param {string} email     - User's email address
 * @param {string} password  - User's plain password (backend hashes it)
 * @returns {Promise<object>}
 */
async function apiRealRegister(fullName, email, password) {
  const response = await fetch(`${API_BASE_URL}/v1/users/`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      full_name: fullName,
      email,
      password,
    }),
  });

  const data = await response.json();

  if (!response.ok) {
    throw { success: false, message: data.detail || "Registration failed." };
  }

  return { success: true, ...data };
}

/**
 * ─── PUBLIC REGISTER API ───
 * Main register function used by components.
 *
 * @param {string} fullName - User's full name
 * @param {string} email    - User's email
 * @param {string} password - User's password
 * @returns {Promise<object>}
 */
export async function registerUser(fullName, email, password) {
  if (USE_MOCK) {
    return apiMockRegister(fullName, email, password);
  }
  return apiRealRegister(fullName, email, password);
}

/**
 * ─── TOKEN MANAGEMENT ───
 * Stores/retrieves the JWT token and user data in localStorage.
 * In production, consider httpOnly cookies for better security.
 */

/** Save auth data to localStorage after successful login */
export function saveAuthData(data) {
  localStorage.setItem("smartgym_token", data.token);
  localStorage.setItem("smartgym_user_id", data.user_id);
  localStorage.setItem("smartgym_role", data.role);
}

/** Retrieve the stored JWT token */
export function getToken() {
  return localStorage.getItem("smartgym_token");
}

/** Retrieve the stored user role */
export function getUserRole() {
  return localStorage.getItem("smartgym_role");
}

/** Clear all auth data (for logout) */
export function clearAuthData() {
  localStorage.removeItem("smartgym_token");
  localStorage.removeItem("smartgym_user_id");
  localStorage.removeItem("smartgym_role");
}

/** Check if user is currently authenticated */
export function isAuthenticated() {
  return !!getToken();
}

